# run: conda env create --file environment.yml
name: jupyter-libertem-proxy
channels:
  - conda-forge
dependencies:
  - jupyterlab>=2
  - jupyterlab_server
  - jupyter_conda
  - pip
  - pip:
#      - libertem>=0.7.0
      - -r file:requirements.txt
